### ISSUE TITLE
App does nothing. Will not allow me to "execute" "run" the entire app.

### ISSUE THREAD

**Issue by Nushaga** [Floogen/Stardrop#105]
I installed Stardrop last night and it worked great. Until the first time I closed it. Then it wouldn't re-open no matter what I did. So I deleted every trace of it I could find. Reinstalled it, and it worked fine, once. I connected all of my mods to it for Stardew, and then i ran the game, and it crashed, and now i can not get it to re-open no matter what I do. I feel as if I am going insane, I just had to enable all of my mods and will have to go through and manually disable the ones causing issues right now. Any idea on what to do? I Dont know how to get a log for you because it won't even open.

**Comment by ImaanBontle** [comment]
@Nushaga I had a similar problem when my computer crashed. Turns out the settings.json file was corrupted. Deleting it fixed things (it doesn't affect your mods, as those are separate profile.json files).

This may not be your issue but may be worth trying. If you're on Windows, it's in the %AppData%/Stardrop folder. If you try to open settings.json and it shows nonsense characters, it's probably corrupted.

**Comment by Floogen** [comment]
This should be resolved with v1.0.0-beta.37. If it is not, please do let me know.
