### ISSUE TITLE
Stardrop using disabled mods [Linux]

### ISSUE THREAD

**Issue by 65942** [Floogen/Stardrop#115]
[log.txt](https://github.com/Floogen/Stardrop/files/11186089/log.txt)
[SMAPI-latest.txt](https://github.com/Floogen/Stardrop/files/11186097/SMAPI-latest.txt)
May be related to #77

Starting the game via Steam loads every mod that I have installed rather than just the ones I selected. Starting the game via Stardrop does not give me that issue so my current work around is with the `"FULL_PATH_TO_STARDROP_Internal" --start-smapi true %command%` launch option

**Comment by Floogen** [comment]
That seems like expected behavior. If you start the game via Steam without Stardrop, then by default SMAPI will load all readable mods.

Those launch options are correct [per the documentation](https://floogen.gitbook.io/stardrop/guides/add-stardrop-to-steam), though you can omit the `--start-smapi true` component if you would like Stardrop to appear before launching the game.

If I misunderstood the issue, please do let me know and I will reopen this.
