### ISSUE TITLE
Config file reseting every time startdrop restart

### ISSUE THREAD

**Issue by LouvAndTech** [Floogen/Stardrop#118]
First thanks for developing startdrop it's a real game changer for player like me.

## Description : 
I have a profile with multiple mods enable, and I changed the config file for multiple of them, tried changing it from [Generic Mod Config Menu](https://www.nexusmods.com/stardewvalley/mods/5098) and directly changing the json itself.

If I don't close Stardrop and only close the game, then restart it everything stay as intended.
But If I close Stardrop, all configs file reset to the default state on the next launch.

## Config 
I'm running MacOs Ventura 
With Stardrop V1.0.0-beta37

Hope someone has an idea.

**Comment by macpherb** [comment]
I am having a similar issue. If I change the config in Stardrop, directly in the folder, or in the GMCM, when I restart the game, it resets the config. This is happening with many different mods, but not all. I can give a list of some that I noticed it happening on (20+), but I don't know that it would be particularly helpful. I am playing on PC and I was using V1.0.0-beta37. I have removed it and am running the game just using SMAPI and the issue is not persisting.

Please let me know if I can provide any further information. Thank you for this really overall helpful mod manager. I hope this can be resolved (or you can help me figure out what I may be doing wrong) so that I can continue using Stardrop again.

**Comment by alexistheinfamous** [comment]
This is something I'm having an issue with as well! I'm new to stardrop, so I'm not sure if I'm doing something wrong, but I'll often log on and find fences back in place that I know I've disabled several times, and things like my fishing overlay will reset as well. If anyone finds a solution, please let me know!

**Comment by Floogen** [comment]
This should be resolved with v1.0.0-beta.38! If you are still having problems, please do let me know.
